package rpg;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author franc
 */
public class Personagens extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Personagens() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        setSize(1000, 720);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(this);
        LÍVIA.setVisible(false);
        MAX1.setVisible(false);
        BECCA1.setVisible(false);
        SCOTT.setVisible(false);
        psL.setVisible(false);
        psS.setVisible(false);
        psB.setVisible(false);
        psM.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPasswordField1 = new javax.swing.JPasswordField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vel1 = new javax.swing.JLabel();
        força1 = new javax.swing.JLabel();
        intg1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vel = new javax.swing.JLabel();
        força = new javax.swing.JLabel();
        intg = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        scott1 = new javax.swing.JRadioButton();
        max1 = new javax.swing.JRadioButton();
        becca1 = new javax.swing.JRadioButton();
        lívia1 = new javax.swing.JRadioButton();
        lívia = new javax.swing.JRadioButton();
        scott = new javax.swing.JRadioButton();
        max = new javax.swing.JRadioButton();
        becca = new javax.swing.JRadioButton();
        LÍVIA = new javax.swing.JLabel();
        BECCA1 = new javax.swing.JLabel();
        MAX1 = new javax.swing.JLabel();
        SCOTT = new javax.swing.JLabel();
        psL = new javax.swing.JLabel();
        psB = new javax.swing.JLabel();
        psM = new javax.swing.JLabel();
        psS = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel5.setText("VELOCIDADE:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 80, 110, 19);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel6.setText("FORÇA:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 20, 70, 19);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel7.setText("INTELIGÊNCIA:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 50, 120, 19);

        vel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vel1.setText(" ");
        jPanel2.add(vel1);
        vel1.setBounds(130, 80, 140, 17);

        força1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        força1.setText(" ");
        jPanel2.add(força1);
        força1.setBounds(90, 20, 140, 17);

        intg1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intg1.setText(" ");
        jPanel2.add(intg1);
        intg1.setBounds(140, 50, 140, 17);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(530, 520, 330, 140);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel2.setText("FORÇA:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 70, 35);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel3.setText("VELOCIDADE:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 120, 19);

        jLabel4.setBackground(new java.awt.Color(255, 102, 51));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel4.setText("INTELIGENCIA:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 50, 130, 19);

        vel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(vel);
        vel.setBounds(120, 80, 180, 20);

        força.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        força.setText(" ");
        jPanel1.add(força);
        força.setBounds(80, 20, 130, 17);

        intg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intg.setText(" ");
        jPanel1.add(intg);
        intg.setBounds(130, 50, 150, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 520, 330, 140);

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/DESING/PERSONAGENS/start.png"))); // NOI18N
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(230, 10, 560, 210);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(870, 590, 130, 40);

        scott1.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup2.add(scott1);
        scott1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        scott1.setText("SCOTT");
        scott1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scott1ActionPerformed(evt);
            }
        });
        getContentPane().add(scott1);
        scott1.setBounds(850, 140, 140, 50);

        max1.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup2.add(max1);
        max1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        max1.setText("MAX");
        max1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                max1ActionPerformed(evt);
            }
        });
        getContentPane().add(max1);
        max1.setBounds(850, 220, 140, 50);

        becca1.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup2.add(becca1);
        becca1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        becca1.setText("BECCA");
        becca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                becca1ActionPerformed(evt);
            }
        });
        getContentPane().add(becca1);
        becca1.setBounds(850, 300, 140, 50);

        lívia1.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup2.add(lívia1);
        lívia1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lívia1.setText("LÍVIA");
        lívia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lívia1ActionPerformed(evt);
            }
        });
        getContentPane().add(lívia1);
        lívia1.setBounds(850, 380, 140, 50);

        lívia.setBackground(new java.awt.Color(255, 102, 51));
        buttonGroup1.add(lívia);
        lívia.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lívia.setText("LÍVIA");
        lívia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                líviaActionPerformed(evt);
            }
        });
        getContentPane().add(lívia);
        lívia.setBounds(30, 380, 140, 50);

        scott.setBackground(new java.awt.Color(255, 102, 51));
        buttonGroup1.add(scott);
        scott.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        scott.setText("SCOTT");
        scott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scottActionPerformed(evt);
            }
        });
        getContentPane().add(scott);
        scott.setBounds(30, 140, 140, 50);

        max.setBackground(new java.awt.Color(255, 102, 51));
        buttonGroup1.add(max);
        max.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        max.setText("MAX");
        max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxActionPerformed(evt);
            }
        });
        getContentPane().add(max);
        max.setBounds(30, 220, 140, 50);

        becca.setBackground(new java.awt.Color(255, 102, 51));
        buttonGroup1.add(becca);
        becca.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        becca.setText("BECCA");
        becca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beccaActionPerformed(evt);
            }
        });
        getContentPane().add(becca);
        becca.setBounds(30, 300, 140, 50);

        LÍVIA.setForeground(new java.awt.Color(255, 255, 255));
        LÍVIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/DESING/PERSONAGENS/LIVIA.gif"))); // NOI18N
        getContentPane().add(LÍVIA);
        LÍVIA.setBounds(220, 160, 420, 450);

        BECCA1.setForeground(new java.awt.Color(255, 255, 255));
        BECCA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/DESING/PERSONAGENS/BECCA.gif"))); // NOI18N
        getContentPane().add(BECCA1);
        BECCA1.setBounds(120, 120, 420, 450);

        MAX1.setForeground(new java.awt.Color(255, 255, 255));
        MAX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/DESING/PERSONAGENS/MAX.gif"))); // NOI18N
        getContentPane().add(MAX1);
        MAX1.setBounds(220, 130, 420, 450);

        SCOTT.setForeground(new java.awt.Color(255, 255, 255));
        SCOTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/DESING/PERSONAGENS/200.gif"))); // NOI18N
        getContentPane().add(SCOTT);
        SCOTT.setBounds(220, 140, 420, 450);

        psL.setForeground(new java.awt.Color(255, 255, 255));
        psL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/DESING/PERSONAGENS/livia espelho.gif"))); // NOI18N
        getContentPane().add(psL);
        psL.setBounds(580, 160, 420, 450);

        psB.setForeground(new java.awt.Color(255, 255, 255));
        psB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/DESING/PERSONAGENS/becca espelho.gif"))); // NOI18N
        getContentPane().add(psB);
        psB.setBounds(460, 130, 420, 450);

        psM.setForeground(new java.awt.Color(255, 255, 255));
        psM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/DESING/PERSONAGENS/max espelho.gif"))); // NOI18N
        getContentPane().add(psM);
        psM.setBounds(570, 150, 420, 450);

        psS.setForeground(new java.awt.Color(255, 255, 255));
        psS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/DESING/PERSONAGENS/SCOT ESPELHO.gif"))); // NOI18N
        getContentPane().add(psS);
        psS.setBounds(560, 150, 420, 450);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/DESING/CENÁRIOS/SELEÇÃO.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        int intgg = Integer.parseInt(intg.getText());
       int intgg1 = Integer.parseInt(intg1.getText());
       
       
       if(intgg > intgg1){
            if(scott.isSelected()){
                new VENCEDOR().setVisible(true);
            }
            if(becca.isSelected()){
                new VENCEDOR_BECCA().setVisible(true);
            }
            if(max.isSelected()){
                new VENCEDOR_MAX().setVisible(true);
            }
            if(lívia.isSelected()){
                new VENCEDOR_LIVIA().setVisible(true);
            }
           
        }else if(intgg < intgg1){
            if(scott1.isSelected()){
                new VENCEDOR().setVisible(true);
            }
            if(becca1.isSelected()){
                new VENCEDOR_BECCA().setVisible(true);
            }
            if(max1.isSelected()){
                new VENCEDOR_MAX().setVisible(true);
            }
            if(lívia1.isSelected()){
                new VENCEDOR_LIVIA().setVisible(true);
            }
            
        }else{
            new EMPATE().setVisible(true);
        }
       
    }//GEN-LAST:event_startActionPerformed

    private void scottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scottActionPerformed

SCOTT.setVisible(true);
LÍVIA.setVisible(false);
BECCA1.setVisible(false);
MAX1.setVisible(false);
/*HABILIDADES*/
        força.setText("300");
        intg.setText("120");
        vel.setText("150");


    }//GEN-LAST:event_scottActionPerformed

    private void líviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_líviaActionPerformed
SCOTT.setVisible(false);
LÍVIA.setVisible(true);
BECCA1.setVisible(false);
MAX1.setVisible(false);
/*HABILIDADES*/
        força.setText("270");
        intg.setText("111");
        vel.setText("100");

    }//GEN-LAST:event_líviaActionPerformed

    private void maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxActionPerformed
SCOTT.setVisible(false);
LÍVIA.setVisible(false);
BECCA1.setVisible(false);
MAX1.setVisible(true);
/*HABILIDADES*/
        força.setText("220");
        intg.setText("100");
        vel.setText("80");
    }//GEN-LAST:event_maxActionPerformed

    private void beccaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beccaActionPerformed
SCOTT.setVisible(false);
LÍVIA.setVisible(false);
BECCA1.setVisible(true);
MAX1.setVisible(false);
/*HABILIDADES*/
        força.setText("350");
        intg.setText("125");
        vel.setText("90");
    }//GEN-LAST:event_beccaActionPerformed

    private void scott1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scott1ActionPerformed
        psL.setVisible(false);
        psS.setVisible(true);
        psB.setVisible(false);
        psM.setVisible(false);
        /*HABILIDADES*/
            força1.setText("300");
            intg1.setText("120");
            vel1.setText("150");
    }//GEN-LAST:event_scott1ActionPerformed

    private void max1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_max1ActionPerformed
        psL.setVisible(false);
        psS.setVisible(false);
        psB.setVisible(false);
        psM.setVisible(true);
        /*HABILIDADES*/
            força1.setText("220");
            intg1.setText("100");
            vel1.setText("80");
    }//GEN-LAST:event_max1ActionPerformed

    private void becca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_becca1ActionPerformed
        psL.setVisible(false);
        psS.setVisible(false);
        psB.setVisible(true);
        psM.setVisible(false);
        /*HABILIDADES*/
            força1.setText("350");
            intg1.setText("125");
            vel1.setText("90");
    }//GEN-LAST:event_becca1ActionPerformed

    private void lívia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lívia1ActionPerformed
       psL.setVisible(true);
        psS.setVisible(false);
        psB.setVisible(false);
        psM.setVisible(false);
        /*HABILIDADES*/
            força1.setText("270");
            intg1.setText("111");
            vel1.setText("100");
    }//GEN-LAST:event_lívia1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Inicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personagens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BECCA1;
    private javax.swing.JLabel LÍVIA;
    private javax.swing.JLabel MAX1;
    private javax.swing.JLabel SCOTT;
    private javax.swing.JRadioButton becca;
    private javax.swing.JRadioButton becca1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel força;
    private javax.swing.JLabel força1;
    private javax.swing.JLabel intg;
    private javax.swing.JLabel intg1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton lívia;
    private javax.swing.JRadioButton lívia1;
    private javax.swing.JRadioButton max;
    private javax.swing.JRadioButton max1;
    private javax.swing.JLabel psB;
    private javax.swing.JLabel psL;
    private javax.swing.JLabel psM;
    private javax.swing.JLabel psS;
    private javax.swing.JRadioButton scott;
    private javax.swing.JRadioButton scott1;
    private javax.swing.JButton start;
    private javax.swing.JLabel vel;
    private javax.swing.JLabel vel1;
    // End of variables declaration//GEN-END:variables
}
